version: "3.7"

services:
  node-ts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gobarber-container
    volumes:
      - ./src:/app/src
    ports:
      - "3333:3333"
      - "8181:8181"
    command:
      yarn dev:docker
